LOGIC_CONSTANT = {'0', '1'}
LOGIC_CAPITAL_LETTER = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'}
NEGATIVE = '!'
CONJUCTION = '/\\'
DISJUCTION = '\\/'
IMPLICATION = '->'
EQUAL = '~'
OPEN_BRACKET = '('
CLOSE_BRACKET = ')'
BINARY_LINK = {CONJUCTION, DISJUCTION, IMPLICATION, EQUAL}
